# Generated by Django 5.1 on 2024-10-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('category_type', models.CharField(max_length=50)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Data',
            fields=[
                ('event_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('start_event_date', models.DateField()),
                ('start_event_time', models.TimeField()),
                ('end_event_date', models.DateField()),
                ('end_event_time', models.TimeField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mahkota_Event.category')),
                ('organized_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mahkota_Event.user')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mahkota_Event.venue')),
            ],
        ),
    ]
